language: node_js
node_js:
- '8'

script:
- npm run build

before_deploy:
# update package versions
- npm version "${TRAVIS_TAG}" --no-git-tag-version --save
- if [[ "${TRAVIS_TAG}" == *"beta"* ]]; then export NPM_TAG="next"; else export NPM_TAG="latest"; fi

deploy:
  provider: npm
  tag: "${NPM_TAG}"
  skip_cleanup: true
  email: igniteui@infragistics.com
  on:
    tags: true
    repo: IgniteUI/igniteui-typedoc-theme
    branch: master
  api_key:
    secure: ntJPGtPKnFli61xf55UGVEEOwb6dLDLLom1My3S+K+7l+vIKIGTMkLKDshV+GksQOmIMxnFP8RzGwmCMPjbeLf8Mv7uoe+xlwfjLghxWUpsNlUUlv0dmqEqXcBG6lsn/QdOR6C59YRmIYkOlaHbJAvQ3Koo5prnmPtjsq/jYhVQIxKU0S3jJ5OuGHuEQq9zIaERuOAqlOh5U1zQ1wHYXXjj4csnZChslvcKkz4mpmB9gxqNsZoB+4iwzrNg6REGpFqjE8bITHPigR9Na9cNj5l6TnYq7P6bk0b+ABrHs5EZEAUQfUtlfwEUtytgUPuyczPz4M4wzWx1nOkaXXuuQhfIVUJ5gfsDFlf2aYgBIjUszzJhTSK0WpH1TATTkI16z/Zqh0DpghELocOPDSNXs3GLRAEXCGpt++BZdnxNLQwGkhy1G9tUY6/aHsf3wWMcaiq6H9aQl1bev81dkMbLtssQqb95TefwIttXowqdFbA1VAmqFAqpXznl0UGq4BwcauGyMhkMul0TDzQlNAMUtovlBAERLGkzISugDarGMIOWLdgOIYqTHjl395MZcpNl8CaWpCOzfBl/WOY62d7YhGz20oM+uDPg4EujfQYVY3v/IFHPqa64ZbB+t50+Nd1s5s5Bku2u9pJkaBR6lQ/2PKTflSKYeFpn+tapmaG33kAc=
